import { Entity } from '../shared/entity';
import { Education, Experience } from './cv.types';

interface CvDataProps {
  name: string;
  email: string;
  phone: string;
  role: string;
  photoUrl?: string;
  summary: string;
  skills: string[];
  education: Education[];
  experience: Experience[];
}

/** Structured CV data generated by the LLM, ready for PDF rendering. */
export class CvData extends Entity<CvDataProps> {
  get name(): string {
    return this.props.name;
  }

  get email(): string {
    return this.props.email;
  }

  get phone(): string {
    return this.props.phone;
  }

  get role(): string {
    return this.props.role;
  }

  get photoUrl(): string | undefined {
    return this.props.photoUrl;
  }

  get summary(): string {
    return this.props.summary;
  }

  get skills(): string[] {
    return [...this.props.skills];
  }

  get education(): Education[] {
    return [...this.props.education];
  }

  get experience(): Experience[] {
    return [...this.props.experience];
  }

  /** Create a CvData instance from LLM-generated JSON. */
  static create(data: CvDataProps): CvData {
    return new CvData(data);
  }

  /** Reconstruct from persisted data. */
  static reconstitute(id: string, data: CvDataProps): CvData {
    return new CvData(data, id);
  }
}
